kind: pipeline
name: TzIndex Pipeline
platform:
  os: linux
  arch: amd64

trigger:
  event:
    - push
    - tag
    - pull_request
#  paths:
#    include:
#      - README.md

environment:
  CGO_ENABLED: 0

steps:
- name: run linter
  image: golangci/golangci-lint:v1.55.2-alpine
  commands:
    - golangci-lint run

- name: scan the files
  image: aquasec/trivy:0.49.1
  commands:
    - trivy fs --exit-code 1 --scanners vuln,config ./
    - trivy config --exit-code 1 ./

- name: go build
  image: golang:1.21.7-alpine3.19
  commands:
    - apk add --no-cache git
    - go vet ./...
    - go test ./...
    - go build ./cmd/...
